### ISSUE TITLE
Cache-Namespaces?

### ISSUE THREAD

**Issue by mathielen** [phpro/annotated-cache#1]
Hi there,

Nice looking library. I want to give it try. But I'm new to all the PSR-6 cache handling. So maybe I just didnt understand something about that yet...

Lets say I have a service with 2 methods, each method is a getSomething($key), so I annotate them like this:

``` php
/**
 * @Cacheable(pools="products")
 */
public function hasProduct($productCode)
{
...
}

/**
 * @Cacheable(pools="products")
 */
public function getProductName($productCode)
{
....
}
```

I want to have all arguments as the key, so I omit the key="" attribute. Why is it that even if I use different pools for both methods that I end up having only one key written in my cache backend (which is redis). I thought that the method's name is taken into account when generating the key, or at least the pool's name...

I'm stuck :(

Your code looks awesome and its definitely a better implementation than the one from https://github.com/TheBigBrainsCompany/TbbcCacheBundle (which is also good)

Thanks for any hint
Markus

**Comment by veewee** [comment]
Hi @mathielen,

Thanks for your question! Currently, this library is at it's first version so it still has some things in it that could be better.
The problem you are facing is that the keygenerator is only taking the method arguments to generate it's key. 
This means that by default, it will not take the method name into account when generating a key.
See: https://github.com/phpro/annotated-cache/blob/master/src/Phpro/AnnotatedCache/Interceptor/CacheableInterceptor.php#L122

The key generation part is pretty much copied from the `TbbcCacheBundle`. In a next version I want to change the [KeyGeneratorInterface](https://github.com/phpro/annotated-cache/blob/master/src/Phpro/AnnotatedCache/KeyGenerator/KeyGeneratorInterface.php). The new interface should be able to handle the interception parameters as well (class name, method, returnValue). 

To temporary fix your problem, there are 2 solutions:
- Add the key and use the expression language. For example:  

```
@Cacheable(pools="products" key="'product::hasProduct-' ~ productCode")
```
- Create your own KeyGenerator. Note that if you do this, you will only have access to the method arguments as described in the section above.

So to conclude: your problem doesn't have anything to do with redis nor PSR-6. It's just one of the downfalls of the current key generator.

I hope both the problam and solution are clear to you now.

**Comment by veewee** [comment]
I've changed the KeyGeneratorInterface and tagged the changes as: [v0.2.0](https://github.com/phpro/annotated-cache/releases/tag/v0.2.0)
By default it will use the classname and method name in the `SimpleKeyGenerator`. This means you won't have to add any key option to your annotations as described above.
